# Generated by Django 3.0.5 on 2020-05-02 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_auto_20200503_0104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fcmdevicetoken',
            name='app_version',
        ),
        migrations.RemoveField(
            model_name='fcmdevicetoken',
            name='platform',
        ),
    ]
